### ISSUE TITLE
Some remarks

### ISSUE THREAD

**Issue by stefaniestevens** [searsia/searsiaserver#7] opened 2016-04-23 12:54 UTC
Dear All,

If you are using the Xpaths: I found out, that you are not allowed to enter a title(or other word) with a space after it. This will give back different errors which makes it hard to find.

And a question. How can I remove 'update failed'? If I try to delete them, I only get an 'delete failed'  but cannot delete it.

Kind regards,
Stefanie

**Comment by djoerd** [comment] 2016-04-24 21:19
I cannot reproduce the error when I enter an XPath query with a space: This seems to go fine.

To enable updates, you have to start the server with the option `--open`.

**Comment by stefaniestevens** [comment] 2016-04-25 09:42
Good morning,

If I enter in the first colum, 'title ', I get the 405 error 'Method not allowed'. 

I opened the server with : java -jar searsiaserver.jar --mother none --open;
If I then try to delete a update failed, it is impossible because you only get a delete failed. We tried it on different computers....

Kind regards,
Stefanie

**Comment by djoerd** [comment] 2016-04-25 11:05
Yes, I get the error 405 too if I add ;title ' (with a space).

If you an update failed, and the resource did not exist before, then it does not exist and cannot be deleted. The messages and the list of resources in the client need some more thinking. Thanks for reporting this.

**Comment by searsia** [comment] 2018-01-06 09:19
This is resolved in Version v1.x.x

**Closed by searsia** 2018-01-06 09:19 UTC
Labels: bug
